import { describe, it, expect, vi, beforeEach } from 'vitest';
import { marketsStore } from './markets.svelte';
import { setupTauriMock, mockMarkets } from './test-fixtures';

// Setup basic Tauri Mocks
vi.mock('@tauri-apps/api/core', () => ({ invoke: vi.fn() }));

describe('MarketsStore Unit Tests', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        marketsStore.clearMarkets();
        marketsStore.markets = [...mockMarkets]; // Inject initial state
    });

    it('should initialize and read the market objects accurately', () => {
        expect(marketsStore.markets.length).toBe(2);
        expect(marketsStore.markets[0].code).toBe('B3');
        expect(marketsStore.markets[1].country).toBe('US');
    });

    
    it('should add a newly drafted market without duplicating arrays incorrectly', () => {
        marketsStore.addMarket({
            name: 'New York Stock Exchange',
            code: 'NYSE',
            country: 'US'
        });

        expect(marketsStore.markets.length).toBe(3);
        const added = marketsStore.markets.find(m => m.code === 'NYSE');
        expect(added).toBeDefined();
        // ID generated by crypto fallback
        expect(added?.id).toBeDefined(); 
    });

    it('should perform partial property updates without polluting sibling objects', () => {
        marketsStore.updateMarket('market:NASDAQ', { name: 'Nasdaq Composite' });
        
        const updated = marketsStore.markets.find(m => m.id === 'market:NASDAQ');
        expect(updated?.name).toBe('Nasdaq Composite');
        expect(updated?.country).toBe('US'); // Unchanged property
    });

    it('should execute raw deletion on standard UI prompts', async () => {
        const result = await marketsStore.deleteMarket('market:B3');
        
        expect(result.success).toBe(true);
        expect(marketsStore.markets.length).toBe(1);
    });

    it('should flush all state bindings during cleanup procedures', () => {
        marketsStore.clearMarkets();
        expect(marketsStore.markets.length).toBe(0);
    });
});
